const express = require('express');
const router = express.Router();
const { verifyToken } = require('../middleware/auth');
const { createLog, getLogs, submitLog, getPendingLogs, reviewLog, getHostScore, setHostScoreOverride, getMyHostStudents } = require('../controllers/logController');
router.post('/', verifyToken, createLog);
router.get('/', verifyToken, getLogs);
router.patch('/:id/submit', verifyToken, submitLog);
router.get('/pending', verifyToken, getPendingLogs);
router.patch('/:id/review', verifyToken, reviewLog);
router.get('/host-score/:studentId', verifyToken, getHostScore);
router.post('/host-score/:studentId', verifyToken, setHostScoreOverride);
router.get('/my-students', verifyToken, getMyHostStudents);
module.exports = router;